### PR TITLE
update random forest part

### PR DESCRIPTION
**Pull request by Siri-Gith1**
Update MS4 with Random Forest Model. please review. thank you

### CODE REVIEW

**Review by kayleeisokay — COMMENTED** [review]
1. Can you move your code before Chloe's?
2. Can you plot the f1-score vs max_depth as well because we should be cross validating to find the model with the best f1-score? 
3. Can you write a quick blurb justifying the parameter lists in your grid search? 
4. Round your `rf2.best_score_` to four decimal places
5. Let's just use top 20 best features
6. Can you do a permutation test as well for the feature importance? We should do this since it's Pavlos's favorite. 
7. Also you can delete the printout of the classification matrix since you made a plot for it.
8. Lastly do you know if do a feature selection prior to running RandomForest helps?

**Review by kayleeisokay — CHANGES_REQUESTED** [review]
Left a list of changes

**Comment by Siri-Gith1** [comment]
Thanks for feedback. I will work on it.  

On Q8, I tried it during hw5, doing feature selection prior to RF. it does not improve. In fact the outcome is the same with or without feature selection.  It could be RF already take care of it in their algorithm.   

> 1. Can you move your code before Chloe's?
> 2. Can you plot the f1-score vs max_depth as well because we should be cross validating to find the model with the best f1-score?
> 3. Can you write a quick blurb justifying the parameter lists in your grid search?
> 4. Round your `rf2.best_score_` to four decimal places
> 5. Let's just use top 20 best features
> 6. Can you do a permutation test as well for the feature importance? We should do this since it's Pavlos's favorite.
> 7. Also you can delete the printout of the classification matrix since you made a plot for it.
> 8. Lastly do you know if do a feature selection prior to running RandomForest helps?
> 9. Also to save yourself time, I don't think you need to gridsearch to find n_estimators. For bagging, just set a high number and go. You won't overfit, it'll just plateau instead (citing pavlos here).

**Comment by kayleeisokay** [comment]
O.K. sounds good. For Q8 it was a recommendation by the professor so I wanted to know. Can you still try it with our data? It might be different than HW5's.

**Comment by Siri-Gith1** [comment]
Kaylee, I updated the MS4 on my branch a while ago.  Shall I create another pull request? thx

**Comment by kayleeisokay** [comment]
Sorry Siri, there are still a couple of things

1. Why are we using different max depths in the f1 score chart? I think the best way to go about this is to calculate f1 and accuracy in the first loop you had. Instead of using cross_val_score, use cross_validate(). 
- I'm wondering why a different randomforest model was used to compute the f1 score?
3. The GridSearch explanation is just definitions. I think we should explain why such ranges were used? Why did you choose min sample leaf 1, 5, 10 instead of 5, 15, 20? Justify the choice
4. Don't hard code lists use range(6, 22, 2) for example.
5. I don't think the explanation of the feature importance is precise enough. model-based importance isn't correct. The built in feature importance is MDI. It doens't make sense that a feature would 'dominate' in random forest given that at each split a random subset of features are chosen.

**Comment by kayleeisokay** [comment]
Merging; Kaylee to take over to expedite things

**Pull request merged**
